### ISSUE TITLE
Suggestion: time events 

### ISSUE THREAD

**Issue by GatoMalandra** [sickmartian/trackendar#1]
Thanks for the effort to make this program.

When viewing an event, it would be ideal to display the time in which registered.

They could answer questions like: what time I take the medication?

You can see for example the delay between the alarm and the actual time the event is executed. You might also graph this delay.

Regards,
Carlos

**Comment by sickmartian** [comment]
Hi Carlos,

Thanks for the interest. Adding the date/time of the event creation should be easy. However supporting multiple types of graphs and slicing the data is something I am saving for a possible pro version (the app didn't take off, so it's not a priority at the moment).

Does something like this work for you?

For events created the same day they were logged:
![For event created the same day as it was logged]
(https://cloud.githubusercontent.com/assets/492246/12105092/3366bb9e-b330-11e5-96eb-b6a33a760d93.png)


For events created on a different day as they were logged:
![For event created on a different day as it was logged](https://cloud.githubusercontent.com/assets/492246/12104987/57141d26-b32f-11e5-8de2-e582fbd01d97.png)

**Comment by GatoMalandra** [comment]
Hello,

Thank you for adding time.

Will there be the ability to display the time in the window where the
history of a specific event is shown (list below the graphic)?

Currently only it appears the month and day and there is enough space to
display the time. Even part of the note if there has been any.

For me it is more useful to see the time in that place. You can quickly
assess the degree of disorder :-)

For instance for Weight (the note would be truncated):

2016
Junuary 12 - 10:35:25 'Doctor off...' 76.9
Junuary 05 - 23:15:50                    78.2
Junuary 01 - 14:01:44                    77.8


Regards,
Carlos


2016-01-04 22:16 GMT-03:00 leuu86@gmail.com <notifications@github.com>:

**Comment by sickmartian** [comment]
Sounds reasonable, I will try to include the time (and date in case it was logged on a different day).
The note is already fully shown below the date of the event.

**Comment by sickmartian** [comment]
Here we go... As before, I had to include the date if the entries are not from the same day, on this screenshot before october 8..
Also there is an example with a big note there as well.

![time](https://cloud.githubusercontent.com/assets/492246/12314845/57625736-ba53-11e5-83a8-95bd44405484.png)

**Comment by GatoMalandra** [comment]
Looks great.

I show "AM" and "PM" in lowercase for the time to be clearer.

Thanks,

Carlos

2016-01-14 0:12 GMT-03:00 leuu86@gmail.com <notifications@github.com>:

**Comment by sickmartian** [comment]
That depends on your locale settings, I don't format it myself.
It's on production already, so I will close this one, let me know if anything comes up.
